-- 01_bronze_layer.sql
-- BRONZE LAYER (Raw Data Ingestion)
USE DATABASE RETAIL_CATALOG;

CREATE OR REPLACE SCHEMA BRONZE;

CREATE OR REPLACE TABLE BRONZE.CUSTOMERS_RAW (
    CUSTOMER_ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    SIGNUP_DATE DATE
);

CREATE OR REPLACE TABLE BRONZE.ORDERS_RAW (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    ORDER_AMOUNT DECIMAL(12,2),
    ORDER_DATE DATE,
    REGION STRING
);

CREATE OR REPLACE TABLE BRONZE.PRODUCTS_RAW (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    PRICE DECIMAL(10,2)
);

CREATE OR REPLACE TABLE BRONZE.RETURNS_RAW (
    RETURN_ID INT,
    ORDER_ID INT,
    RETURN_REASON STRING,
    RETURN_DATE DATE
);